#! /usr/bin/env ruby
require 'pathname'

git_root = `git rev-parse --show-toplevel`.strip

changed_files = `git status --porcelain`.lines
  .select { |line| line.match?(/^\s*[AM\?].*\.rb$/) }
  .map { |line| line.split.last }
  .map { |file| File.join(git_root, file) }

if changed_files.empty?
  puts "\e[31mNo Ruby files changed.\e[0m"
else
  changed_files.each do |file|
    puts ""
    rubocop_command = File.exist?(File.join(git_root, 'Gemfile')) ? 'bundle exec rubocop' : 'rubocop'
    command = "#{rubocop_command} #{ARGV.join(' ')} #{file}"
    puts "\e[36m#{command}\e[0m"
    system(command)
  end
end

